### PR TITLE
Add config button

### PR DESCRIPTION
**Pull request by Chaosmeister**
implements #27 

image

### CODE REVIEW

**Comment by Jieiku** [comment]
Chaosmeister, THANK YOU soooooo much for this!!!!

Quick question, how difficult would it be to also add a "+" button (similar to the plus buttons for creating tasks) directly next to the config button to create swimlanes for a project directly from the bigboard?

**Comment by Chaosmeister** [comment]
> Chaosmeister, THANK YOU soooooo much for this!!!!
> 
> Quick question, how difficult would it be to also add a "+" button (similar to the plus buttons for creating tasks) directly next to the config button to create swimlanes for a project directly from the bigboard?

swimlines do have a few variables to define (position, name), I'd have to look into that, how to offer those

**Comment by Jieiku** [comment]
I was mostly thinking just open the controller by clicking from the bigboard.

I inspected the link and it looks like this:

https://kanboard.example.com/?controller=SwimlaneController&action=create&project_id=4

so if that could be opened in an iframe similar to when you click the task dropdown from bigboard to "Edit the task"



but maybe that is not the best way to do it? I am not sure.

**Comment by Chaosmeister** [comment]
I'll have a look tomorrow 🙂

**Comment by Jieiku** [comment]
This config button works great, I just tested it! Oh man this is really going to make bigboard easier to use!

**Pull request merged**
